import { execSync } from "node:child_process";
import { resolve } from "node:path";

import preact from "@preact/preset-vite";
import type { OutputChunk, OutputOptions } from "rollup";
import { defineConfig } from "vitest/config";

function isOutputChunk(value: unknown): value is OutputChunk {
	return (
		Boolean(value) &&
		typeof value === "object" &&
		"type" in value &&
		(value as { type?: string }).type === "chunk"
	);
}

function resolveGitCommit(): string {
	try {
		return execSync("git rev-parse --short=7 HEAD", {
			cwd: __dirname,
			encoding: "utf-8",
		})
			.trim()
			.slice(0, 7);
	} catch {
		return "";
	}
}

const gitCommit = resolveGitCommit();

export default defineConfig(({ command, mode }) => {
	const isDevServer = command === "serve";
	const viewerPort = Number(process.env.CODEMEM_DEV_VIEWER_PORT || "38899");

	return {
		define: {
			__CODEMEM_GIT_COMMIT__: JSON.stringify(gitCommit),
		},
		resolve: {
			alias: {
				react: "preact/compat",
				"react-dom": "preact/compat",
				"react-dom/test-utils": "preact/test-utils",
				"react/jsx-runtime": "preact/jsx-runtime",
			},
		},
		// Dev-server mode: HMR-friendly config. The dev server serves
		// packages/ui/index.html (generated by scripts/make-dev-html.mjs)
		// which loads /src/app.ts as an ES module. /api and /assets are
		// proxied to the tsx-watched viewer on CODEMEM_DEV_VIEWER_PORT.
		server: isDevServer
			? {
					// Default host ("localhost") resolves dual-stack on macOS/Linux
					// per /etc/hosts without exposing external interfaces. Overriding
					// to "::" would bind 0.0.0.0 + :: (all interfaces).
					port: Number(process.env.CODEMEM_DEV_VITE_PORT || "5173"),
					strictPort: false,
					proxy: {
						"/api": { target: `http://127.0.0.1:${viewerPort}`, changeOrigin: false },
						"/assets": { target: `http://127.0.0.1:${viewerPort}`, changeOrigin: false },
					},
				}
			: undefined,
		// Build mode: production IIFE bundle staged into viewer-server/static.
		build: isDevServer
			? undefined
			: {
					outDir: resolve(__dirname, "../viewer-server/static"),
					emptyOutDir: false,
					lib: {
						entry: resolve(__dirname, "src/app.ts"),
						name: "OpencodeMemViewer",
						formats: ["iife"],
						fileName: () => "app.js",
					},
					rollupOptions: {
						output: {
							inlineDynamicImports: true,
						},
					},
					sourcemap: mode === "development",
					minify: false,
				},
		plugins: [
			preact(),
			...(isDevServer || mode === "development"
				? []
				: [
						{
							name: "strip-sourcemap-url",
							generateBundle(_options: OutputOptions, bundle) {
								for (const output of Object.values(bundle)) {
									if (isOutputChunk(output) && output.fileName === "app.js") {
										output.code = output.code.replace(/^\s*\/\/#\s*sourceMappingURL=.*$/gm, "");
									}
								}
							},
						},
					]),
		],
		esbuild: {
			legalComments: "none",
		},
		test: {
			environment: "jsdom",
			name: "ui",
		},
	};
});
