/* API fetch wrappers — barrel re-export of the split modules. The
 * viewer HTTP endpoints were broken up into api/ (types.ts,
 * internal.ts, runtime.ts, stats.ts, memories.ts, config.ts, sync.ts,
 * coordinator-admin.ts) during the decomposition; this file now only
 * keeps the public API stable for `import * as api from "../lib/api"`
 * call sites. */

export { loadConfig, loadObserverStatus, saveConfig } from "./api/config";
export {
	archiveCoordinatorAdminGroup,
	createCoordinatorAdminGroup,
	createCoordinatorAdminScope,
	createCoordinatorInvite,
	disableCoordinatorAdminDevice,
	enableCoordinatorAdminDevice,
	grantCoordinatorAdminScopeMember,
	loadCoordinatorAdminDevices,
	loadCoordinatorAdminGroups,
	loadCoordinatorAdminGroupsFiltered,
	loadCoordinatorAdminJoinRequests,
	loadCoordinatorAdminScopeMembers,
	loadCoordinatorAdminScopes,
	loadCoordinatorAdminStatus,
	removeCoordinatorAdminDevice,
	renameCoordinatorAdminDevice,
	renameCoordinatorAdminGroup,
	reviewCoordinatorAdminJoinRequest,
	revokeCoordinatorAdminScopeMember,
	unarchiveCoordinatorAdminGroup,
	updateCoordinatorAdminScope,
} from "./api/coordinator-admin";
export {
	forgetMemory,
	loadMemories,
	loadMemoriesPage,
	loadSummaries,
	loadSummariesPage,
	moveMemoryProject,
	tracePack,
	updateMemoryVisibility,
} from "./api/memories";
export { loadProjects, loadRuntimeInfo, pingViewerReady } from "./api/runtime";
export { loadRawEvents, loadSession, loadStats, loadUsage } from "./api/stats";
export type {
	CreatedRecipientInvite,
	DeviceIdentityBindingCommitV1,
	DeviceIdentityBindingOutcomeV1,
	DeviceIdentityBindingPreviewRequestV1,
	DeviceIdentityBindingPreviewV1,
	DeviceIdentityBindingSelectionV1,
	DeviceIdentityInventoryItemV1,
	DeviceIdentityInventoryStateV1,
	DeviceIdentityInventoryV1,
	InspectInviteResult,
	LegacyTeamSetupAccessDeltaV1,
	LegacyTeamSetupAssignmentExpectationV1,
	LegacyTeamSetupCandidateSummaryV1,
	LegacyTeamSetupDetailResponseV1,
	LegacyTeamSetupDeviceV1,
	LegacyTeamSetupErrorCode,
	LegacyTeamSetupFinishResponseV1,
	LegacyTeamSetupIdentityChoiceV1,
	LegacyTeamSetupMutationResponseV1,
	LegacyTeamSetupProjectV1,
	LegacyTeamSetupStatusV1,
	LegacyTeamSetupSummaryResponseV1,
	RecipientInvitationKind,
	RecipientInvitePreviewRequest,
	RecipientInvitePreviewResult,
	RecipientOnboardingPreviewV1,
	RecipientOnboardingProjectV1,
	RecipientPolicyBlockedItemV1,
	RecipientPolicyEdgeChangeV1,
	RecipientPolicyEdgeCommitOutcomeV1,
	RecipientPolicyEdgeCommitRequestV1,
	RecipientPolicyEdgeCommitResultV1,
	RecipientPolicyEdgeEffectiveDeviceV1,
	RecipientPolicyEdgeIdentitySummaryV1,
	RecipientPolicyEdgeOutcomeV1,
	RecipientPolicyEdgePreviewProjectV1,
	RecipientPolicyEdgePreviewRequestV1,
	RecipientPolicyEdgePreviewResponseV1,
	RecipientPolicyEdgeRecipientRefV1,
	RecipientPolicyEdgeSelectedRecipientV1,
	RecipientPolicyIdentityDeviceV1,
	RecipientPolicyIdentityV1,
	RecipientPolicyIntentGraphV1,
	RecipientPolicyProjectRecipientV1,
	RecipientPolicyReconciliationReadState,
	RecipientPolicyReconciliationStatusV1,
	RecipientPolicyReviewBulkResultV1,
	RecipientPolicyReviewDecisionV1,
	RecipientPolicyReviewItemV1,
	RecipientPolicyReviewListV1,
	RecipientPolicyReviewOptionV1,
	RecipientPolicyReviewPreviewDeviceV1,
	RecipientPolicyReviewPreviewProjectV1,
	RecipientPolicyReviewPreviewV1,
	RecipientPolicyReviewResolveRequestV1,
	RecipientPolicyReviewResolveResultV1,
	RecipientPolicyReviewResolveStatusV1,
	RecipientPolicyTeamMembershipV1,
	RecipientPolicyTeamRenameErrorCode,
	RecipientPolicyTeamRenameResultV1,
	RecipientPolicyTeamV1,
} from "./api/sync";
export {
	acceptDiscoveredPeer,
	advanceShareOperation,
	claimLegacyDeviceIdentity,
	clearLegacyTeamSetupDecision,
	commitDeviceIdentityBindings,
	commitRecipientPolicyEdges,
	createActor,
	createProjectInvite,
	createRecipientInvite,
	DeviceIdentityBindingApiError,
	deactivateActor,
	deletePeer,
	deleteSharingDomainProjectMapping,
	enrollPeer,
	finishLegacyTeamSetup,
	forgetProjectInventoryMemories,
	importCoordinatorInvite,
	inspectCoordinatorInvite,
	LegacySharedReviewConfirmationError,
	LegacyTeamSetupApiError,
	loadCoordinatorGroupPreferences,
	loadDeviceIdentityInventory,
	loadLegacyTeamSetupDetail,
	loadLegacyTeamSetupSummary,
	loadPairing,
	loadProjectScopeInventory,
	loadRecipientPolicyIntent,
	loadRecipientPolicyReconciliationStatus,
	loadRecipientPolicyReview,
	loadShareOperation,
	loadShareOperations,
	loadSharingDomainSettings,
	loadSyncActors,
	loadSyncStatus,
	mergeActor,
	ProjectForgetConfirmationError,
	ProjectInviteAcceptanceError,
	previewDeviceIdentityBindings,
	previewProjectInvite,
	previewRecipientInvite,
	previewRecipientPolicyEdges,
	RecipientPolicyEdgesStaleError,
	RecipientPolicyReviewStaleError,
	RecipientPolicyTeamRenameApiError,
	reassignLegacySharedReviewGroup,
	reassignProjectInventoryProject,
	refreshLegacyTeamSetupCandidate,
	renameActor,
	renamePeer,
	renameRecipientPolicyTeam,
	resolveRecipientPolicyReview,
	resolveRecipientPolicyReviewBulk,
	SharingDomainGuardrailConfirmationError,
	saveCoordinatorGroupPreferences,
	saveLegacyTeamSetupAssignment,
	saveLegacyTeamSetupDecision,
	saveLegacyTeamSetupProjectMapping,
	saveSharingDomainProjectMapping,
	saveSharingDomainProjectMappings,
	triggerSync,
	updatePeerIdentity,
	updatePeerScope,
} from "./api/sync";
export type {
	AcceptDiscoveredPeerResult,
	CoordinatorInviteResult,
	ImportInviteResult,
	PackTrace,
	PackTraceCandidate,
	PaginatedResponse,
	RuntimeInfo,
	SyncRunItem,
	SyncRunResponse,
	UpdateStatus,
} from "./api/types";
export { loadUpdateStatus, unavailableUpdateStatus } from "./api/update-status";
