import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { generateSQLiteDrizzleJson, generateSQLiteMigration } from "drizzle-kit/api";
import { schema as drizzleSchema } from "../src/schema.js";

const prev = await generateSQLiteDrizzleJson({});
const cur = await generateSQLiteDrizzleJson(drizzleSchema);
const statements = await generateSQLiteMigration(prev, cur);

const idempotentStatements = statements.map((statement) =>
	statement
		.replace(/^CREATE TABLE /, "CREATE TABLE IF NOT EXISTS ")
		.replace(/^CREATE UNIQUE INDEX /, "CREATE UNIQUE INDEX IF NOT EXISTS ")
		.replace(/^CREATE INDEX /, "CREATE INDEX IF NOT EXISTS "),
);

const output = `/**
 * AUTO-GENERATED by scripts/generate-test-schema.ts
 *
 * Do not edit manually. Regenerate with:
 * pnpm --filter @codemem/core run generate:test-schema
 */

export const TEST_SCHEMA_BASE_DDL =
\t${JSON.stringify(idempotentStatements.join("\n"))};
`;

const outputPath = resolve(import.meta.dirname, "../src/test-schema.generated.ts");
writeFileSync(outputPath, output, "utf-8");
