// allow: SIZE_OK - package-root public API barrel contains re-exports only and intentionally preserves one stable root import surface.
export {
  RESIDENCY_STATES,
  RESOLVED_MODEL_SOURCES,
  TASK_STATUSES,
  createTaskRecord,
  markRecordLostForReconciliation,
  messageability,
  transitionTaskRecord,
} from "./state"
export type {
  Messageability,
  ResidencyState,
  ResolvedModelRecord,
  ResolvedModelSource,
  TaskNotification,
  TaskRecord,
  TaskRecordInput,
  TaskStatus,
  TaskTransition,
  TaskTransitionAudit,
  TaskTransitionResult,
} from "./state"
export { TaskRecordCollisionError, createTaskRecordStore, resolveStateDir } from "./store"
export type {
  ListTaskRecordsResult,
  PersistedTaskEvent,
  StateDirConfig,
  TaskRecordDiagnostic,
  TaskRecordStore,
} from "./store"
export { createMinimalSenpiResourceLoader } from "./senpi/minimal-resource-loader"
export type { MinimalSenpiResourceLoaderOptions } from "./senpi/minimal-resource-loader"
export {
  SenpiTeamSpecError,
  TEAM_LEAD_SENTINEL,
  ensureTeamRuntimeDirs,
  loadTeamRegistry,
  normalizeSenpiTeamSpec,
  resolveProjectTeamSpecPath,
  resolveTeamMemberInboxDir,
  resolveTeamRuntimeDirs,
  teamStorageBaseDir,
  validateSenpiTeamMembers,
} from "./team"
export type {
  LoadTeamRegistryInput,
  LoadTeamRegistryResult,
  NormalizeSenpiTeamSpecOptions,
  SenpiTeamMemberPorts,
  SenpiTeamSpecErrorCode,
  TeamRegistryEntry,
  TeamRegistryError,
  TeamRuntimeDirs,
  TeamSpecSource,
} from "./team"
export {
  BUILTIN_CATEGORY_DEFAULTS,
  CATEGORY_DESCRIPTIONS,
  CATEGORY_PROMPT_APPENDS,
  DEFAULT_CATEGORIES,
  resolveCategory,
} from "./category"
export type {
  BuiltinCategoryDefinition,
  CategoryModelSelection,
  CategoryResolutionResult,
  ResolvedChildSpec,
  SenpiModelPort,
  SenpiModelRegistryPort,
} from "./category"
export {
  DEFAULT_MAX_CHILD_DEPTH,
  InProcessRunner,
  RunnerError,
  buildSubagentPrompt,
  createChildResourceLoader,
  filterSharedParentTools,
  isTaskOrTeamFamilyTool,
  mergeChildCustomTools,
} from "./runners"
export type {
  ChildHandle,
  ChildSession,
  ChildSessionEvent,
  ChildSessionListener,
  ChildSpec,
  CreateChildSession,
  DepthPolicy,
  InProcessRunnerOptions,
  RunnerFailure,
  RunnerOutcome,
  SharedToolFilterOptions,
  SubagentPromptInput,
} from "./runners"
export {
  RpcCommandError,
  RpcProcessRunner,
  RpcProtocolClient,
  buildAutoUiResponse,
  buildChildArgs,
  buildRpcSpawn,
  classifyChildExit,
  createRpcChildHandle,
  detectBunBinary,
  mapExitOutcomeToError,
  parseExtensionEntries,
  resolveChildSessionDir,
  resolveSenpiExecutable,
  tailStderr,
  terminateRpcChild,
} from "./runners"
export type {
  ChildEventListener,
  ChildExitFacts,
  ChildExitInput,
  ChildExitOutcome,
  CreateRpcChildHandleOptions,
  MalformedLineHandler,
  RpcChildHandle,
  RpcProcessRunnerOptions,
  RpcProtocolClientOptions,
  RpcRunnerSpec,
  RpcSpawnDescriptor,
  RpcSpawnRuntime,
  RunnerErrorFacts,
  TerminateOptions,
} from "./runners"
export {
  NameRegistry,
  TaskConcurrency,
  adaptInProcessHandle,
  adaptRpcHandle,
  createInProcessManagedRunner,
  createParentRegistrySessionContext,
  createRpcManagedRunner,
  createTaskManager,
  decideDepthPolicy,
  findModelReference,
  resolveExecutionMode,
} from "./manager"
export type {
  AdmitResident,
  ChildModelRegistry,
  ChildPlanner,
  ContinueDelivery,
  ContinueResult,
  DepthDecision,
  DepthPolicyInput,
  ExecutionMode,
  ExecutionModeSources,
  InProcessRunnerLike,
  InProcessSessionContext,
  InProcessSessionContextProvider,
  ListScope,
  ListedTask,
  ManagedChildEvent,
  ManagedChildHandle,
  ManagedChildListener,
  ManagedRunner,
  ManagedStartSpec,
  ManagerStartSpec,
  NameRegistration,
  ParentModelRegistryResolver,
  PlanResolution,
  PlanResolutionError,
  ResolvedChildPlan,
  RpcRunnerLike,
  SpawnAdmission,
  StartResult,
  TaskConcurrencyConfig,
  TaskManager,
  TaskManagerOptions,
} from "./manager"
export { defineAgent, loadAgents, mapOmoConfigAgents, registerAgent, resolveToolRule } from "./agents"
export type {
  AgentDefinition,
  AgentDefinitionInput,
  AgentLoaderDiagnostic,
  AgentLoaderDiagnosticKind,
  AgentToolRule,
  LoadAgentsOptions,
  LoadAgentsResult,
} from "./agents"
export {
  buildCompletionDetails,
  buildCompletionMessage,
  completionMessageLines,
  createCompletionNotifier,
  routeCompletion,
  shouldNotifyStatus,
} from "./completion"
export type {
  CompletionDetails,
  CompletionNotifier,
  CompletionNotifierDeps,
  CompletionNotifierStore,
  CompletionRequest,
  DeliveredDecision,
  FlushInput,
  FlushResult,
  NotifyResult,
  ParentNotifier,
  ParentNotifierMessage,
  ParentState,
  RoutingDecision,
  SkipReason,
  TransitionReason,
} from "./completion"
export { AgentLimitReached, createTaskLifecycle } from "./lifecycle"
export type {
  AdmissionResult,
  CleanupResult,
  DestroyCause,
  LifecycleDeps,
  ProcessSignaller,
  ReconcileOutcome,
  ReconcileOutcomeKind,
  ReconcileResult,
  ResidentHandle,
  ResidentSummary,
  ResidencyRegistry,
  TaskLifecycle,
  TeardownSummary,
} from "./lifecycle"
export { DEFAULT_SEND_DELIVERY, createSteeringEngine } from "./steering"
export type {
  CancelOutcome,
  DestructionCause,
  DestructionPort,
  InterruptOutcome,
  SendDelivery,
  SendInput,
  SendOutcome,
  SteeringEngine,
  SteeringPort,
} from "./steering"
export {
  TASK_PROMPT_GUIDELINES,
  TASK_PROMPT_SNIPPET,
  TASK_TOOL_NAME,
  TaskToolParams,
  buildSkillPrepend,
  buildTaskExecute,
  buildTaskToolDescription,
  createFsSkillLoader,
  createTaskTool,
  excerptRendererPromptText,
  excerptRendererText,
  joinRendererTokens,
  linesComponent,
  listTaskAgents,
  listTaskCategories,
  normalizeRendererText,
  rendererVisibleWidth,
  statusThemeColor,
  taskCallLines,
  taskResultLines,
  validateTaskTarget,
} from "./tools/task"
export type {
  ResolveAncestry,
  SkillLoader,
  SkillResolution,
  TaskAgentInfo,
  TaskAncestry,
  TaskCategoryInfo,
  TaskTargetError,
  TaskTargetErrorCode,
  TaskTargetSelection,
  TaskToolContext,
  TaskToolDeps,
  TaskToolDetails,
  TaskToolMode,
  TaskToolParamsStatic,
} from "./tools/task"
export {
  TaskCancelParams,
  TaskSendParams,
  clampWaitTimeout,
  createMemberScopedTaskSendTool,
  createTaskCancelTool,
  createTaskSendTool,
  defaultResolveCallerSessionId,
  finalResponseHead,
  isTerminalStatus,
  runTaskCancel,
  runTaskSend,
  toolResult,
} from "./tools/control"
export type {
  CallerSessionResolver,
  CancelManager,
  CancelResultDetails,
  CancelToolResult,
  MemberScopedTaskSendDeps,
  SendManager,
  SendResultDetails,
  SendToolResult,
  SessionIdCarrier,
  TaskCancelDeps,
  TaskCancelInput,
  TaskSendDeps,
  TaskSendInput,
  TaskSendTeamRouting,
  WaitBounds,
} from "./tools/control"
export {
  TRANSCRIPT_MAX_CHARS,
  TaskOutputParams,
  buildTaskSnapshot,
  childSessionDir,
  createTaskOutputTool,
  defaultTranscriptReader,
  parseSessionTranscript,
  readEventLogTranscript,
  readSessionDirTranscript,
  renderTranscript,
  runTaskOutput,
} from "./tools/output"
export type {
  LostBreadcrumbs,
  OutputManager,
  RenderOptions,
  RenderedTranscript,
  TaskOutputDeps,
  TaskOutputDetails,
  TaskOutputInput,
  TaskOutputToolResult,
  TaskSnapshot,
  TranscriptEntry,
  TranscriptReadResult,
  TranscriptReader,
  TranscriptSource,
} from "./tools/output"
export {
  ackMemberInjection,
  buildMemberUnreadInjection,
  buildPeerMessageEnvelope,
  buildTeamMessage,
  DEFAULT_STALE_RESERVATION_TTL_MS,
  deliverToLead,
  deliverToMember,
  reclaimStaleTeamReservations,
  reconcileTeamMailboxOnSessionStart,
  releaseMemberInjection,
  sendTeamMessage,
} from "./team"
export type {
  AckMemberInjectionInput,
  BuildMemberUnreadInjectionInput,
  BuildTeamMessageOptions,
  DeliverToLeadInput,
  DeliverToMemberInput,
  LeadDeliveryResult,
  LeadMessageNotifier,
  LeadTeamMessage,
  MemberDeliveryResult,
  MemberLiveHandle,
  MessagingDeliveryPort,
  MessagingEngineDeps,
  ReclaimResult,
  ReconcileTeamMailboxDeps,
  ReleaseMemberInjectionInput,
  SendTeamMessageInput,
  SendTeamMessageResult,
} from "./team"
export {
  approveShutdown,
  canClaimTeamTask,
  claimTeamTask,
  createTeamTask,
  DELETABLE_MEMBER_STATUSES,
  getTeamTask,
  isMemberDeletable,
  listTeamTasks,
  rejectShutdown,
  requestShutdown,
  SenpiShutdownError,
  TeamTaskAlreadyClaimedError,
  TeamTaskBlockedByError,
  TeamTaskCrossOwnerUpdateError,
  TeamTaskInvalidTransitionError,
  updateTeamTaskStatus,
} from "./team"
export type {
  ApproveShutdownDeps,
  CreateTeamTaskInput,
  RejectShutdownDeps,
  RequestShutdownDeps,
  SenpiShutdownErrorCode,
  ShutdownMessageKind,
  ShutdownMessenger,
  ShutdownOutboundMessage,
  TeamTaskFilter,
  TeamTasklistContext,
} from "./team"
export {
  createTeam,
  deleteTeam,
  readMemberTaskMap,
  refreshTeamMemberStatuses,
  SenpiTeamRuntimeError,
  toTeamCoreConfig,
} from "./team"
export type {
  CreateTeamDeps,
  CreateTeamResult,
  DeleteTeamDeps,
  DeleteTeamResult,
  MemberStatusPort,
  MemberTaskMap,
  RefreshTeamMemberStatusesDeps,
  SenpiTeamRuntimeErrorCode,
  TeamCoreConfig,
  TeamRuntimeManagerPort,
} from "./team"

export * from "./tools/team"
